### PR TITLE
refactored response object model

### PR DESCRIPTION
**Pull request by sm5art**
I want to change how the Response model works by creating an object that allows intermediary header changing, and overall response changing. 

For the future of this framework, the response should be modified so that more complicated responses like cookies can be used.

i.e
```python
class Response:
    pass
    
    def set_cookie(self, name, value):
         self.add_headers("Cookie":"{}={}".format(name,value))
```
which will be used like this

```python
@app.route("/")
def handler(req, res):
    res.set_cookie("hello", "world")
    return res.json({"hello":"world")
```
where res is instantiated into the handler by the main sanic.py.

This type of structure will allow better response formulation rather than using the bare response types and pushing in the headers manually. We can write stuff like cookies that will be reused.

My next PR will be implementing cookies. 

This is experimental, I just want to know what you think

### CODE REVIEW

**Comment by sm5art** [comment]
bump

**Comment by channelcat** [comment]
As much as I dislike adding more arguments to the request handlers, this makes sense and makes middleware much more useful.  I'll merge it in :)

**Comment by sm5art** [comment]
ill resolve merge conflicts

**Comment by channelcat** [comment]
I can get them - I'm adding in response as an argument for middleware and exceptions, and adding tests

**Comment by channelcat** [comment]
Alright, I put the changes in the sm5art-cookies branch.  Overall the performance dipped by 1kreq/sec.  I'd like to hold off until we can figure out why it slowed down and fix it.

from sm5art-cookies branch:
Test main:
python3 tests/performance/sanic/simple_server_pip.py 8000
Test new:
python3 tests/performance/sanic/simple_server.py 8000

Benchmark:
wrk -c 100 -t 1 http://127.0.0.1:8000/
Main Requests/sec:  28805.95
New Requests/sec:  27756.66

**Comment by channelcat** [comment]
Thinking of an alternative pattern, just in case:

```python
@app.middleware('request')
async def some_auth_middleware(request):
    # Some auth logic
    request._set_the_cookies = True

@app.middleware('response')
async def some_auth_middleware(request, response):
    if request._set_the_cookies:
        response.cookies['my-cookie'] = 'my-value'
```

**Comment by sm5art** [comment]
ill take a look into it

**Comment by sm5art** [comment]
i like your idea of using middleware to use the new response object.
I think that the performance issues comes from creating an extra response object with each handler

**Comment by davidbgk** [comment]
@sm5art maybe using `__slots__` on your `Response` class might speed up the creation?

**Comment by sm5art** [comment]
i think using python classes will be too slow. will look into different methods of structuring this.

**Comment by davidbgk** [comment]
I use to have good perfs inheriting from namedtuples, not sure if it's pertinent here though.

**Comment by sm5art** [comment]
hmm this is weird, i ran the benchmark: the sm5art-cookies branched had Requests/sec:  36208.95

and the master branch had Requests/sec:   3219.30. 

Something is broken in the master branch

**Comment by sm5art** [comment]
22 ms average latency, on master compared to 3 ms average latency on sm5art-cookies, let me diff the two branches and see what changed in the server logic.

**Comment by sm5art** [comment]
the blueprint feature merge broke latency, tried a benchmark on this commit f2757bc0743f83ea9c12bd936644c936ca61090f, i got Requests/sec:  38994.25

**Comment by sm5art** [comment]
im going to close this pr, and work on making a middleware version

**Pull request closed without merging**
