### PR TITLE
Improve Documentation.

### PR DESCRIPTION
**Pull request by yunstanford**
This PR includes:

1. Add sphinx auto-doc support, doc builds will extract doc_string automatically.
2. Add `API Reference` section. Adding api reference in Documentation is important. It's better to provide that in Documentation instead of letting users find anything they need in codebase directly.
3. Fixes doc_build warnings

I also suggest that we should write doc_string when you are writing sth that will be public to users.
`sphinx auto-doc` will extract out these doc_strings and put them in Documentation, `API references`.

### CODE REVIEW

**Comment by lcDotcom** [comment]
it'd be great to have API reference section.

**Comment by yunstanford** [comment]
Can we also merge this in if no objections?

**Comment by r0fls** [comment]
@yunstanford shamefully I don't know how to review this -- are you able to give me instructions for deploying the docs changes locally? Is it just the below? How do I start the sphinx server?

```sphinx-apidoc -fo docs/_api/ sanic
sphinx-build -b html docs docs/_build```

**Comment by yunstanford** [comment]
If you have installed all dependencies, then simply do `make html` in `/docs`. Then you can see those static pages in `_build` directory.

**Pull request merged**
