### PR TITLE
only install ujson and uvloop with cpython on non windows machines

### PR DESCRIPTION
**Pull request by abuckenheimer**
suggested by @messense in #916

### CODE REVIEW

**Comment by r0fls** [comment]
We've seen a lot of PRs claiming to fix this. I would like to see multiple Windows users verify this fix works for them before merging this.

**Comment by abuckenheimer** [comment]
Obviously this doesn't help with httptools on windows, still need to go through the visual c++ rigamarole there but I've gotten this installed on windows 10/7 no problem with python 3.6.3.

**Comment by r0fls** [comment]
That makes sense. By "seen a lot of" I actually mean we've merged a lot of potential Windows fixes around removing unsupported dependencies 😂  which is why I would like to see another Windows user chime in here and verify this helps in some way, particularly since I thought we were doing this exact thing (or something very similar) at one point ¯\\_(ツ)_/¯

There is always docker for windows by the way ;)

**Comment by abuckenheimer** [comment]
😆 certainly one way to test something, if you can find any of those old merges shoot me one, I'd be curious to see what didn't work. Also unfortunately no docker on Windows 7 yet haha

**Comment by r0fls** [comment]
I guess just these: https://github.com/channelcat/sanic/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+windows

**Comment by alexandertsema** [comment]
I've tested on my Windows 10 x64, works like a charm. Vote for merge.

**Comment by alexandertsema** [comment]
when will it be released with a new version? @seemethere

**Pull request merged**
