### PR TITLE
fix multiple worker problem

### PR DESCRIPTION
**Pull request by r0fls**
Addresses issue #203. Note that the creator of uvloop advises against conforming to wsgi for asyncio web servers. See https://github.com/python/asyncio/issues/481#issuecomment-271098847

### CODE REVIEW

**Comment by r0fls** [comment]
This change also removes some unnecessary code and incorrect logging messages.

**Comment by r0fls** [comment]
@seemethere I'm still working on the tests -- when you use serve_multiple directly it's causing an issue when rebinding to the port. Give me a couple hours before merging please, as I'll be adding a test case for this and fixing the issue with using serve_multiple directly.

**Comment by seemethere** [comment]
@r0fls Will do, thanks for all the good work!

**Comment by r0fls** [comment]
Well, that didn't go as planned... the utils for testing don't appear to be working with this, which will require investigation. So, I've disabled the multiprocessing tests for now. Since MP wasn't really working before, this is still a significant improvement. The below example shows this is working:

```python
import asyncio
import uvloop
from sanic.response import text

import os
from sanic import Sanic

app = Sanic(__name__)

@app.route('/')
async def hello(request):
    print(os.getpid())
    return text("OK")

if __name__ == '__main__':
    app.run(workers=4)
```

Then you can see multiple processes responding:

```
wrk -t50 -c100 http://localhost:8000
3704
3703
3704
3701
3703
3701
3704
3702
```

You should also see improvements from `wrk`. I clocked in at this with 4 workers:

```
$ wrk -t50 -c100 http://localhost:8000
Running 10s test @ http://localhost:8000
  50 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.70ms    1.01ms  10.75ms   72.88%
    Req/Sec   746.49    181.38     6.51k    82.84%
  372222 requests in 10.10s, 45.79MB read
Requests/sec:  36856.63
Transfer/sec:      4.53MB
```

vs this with 1

```
$ wrk -t50 -c100 http://localhost:8000
Running 10s test @ http://localhost:8000
  50 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.18ms    1.81ms  15.60ms   60.86%
    Req/Sec   388.54     75.63   808.00     67.54%
  193713 requests in 10.03s, 23.83MB read
Requests/sec:  19317.26
Transfer/sec:      2.38MB
```

**Pull request merged**
