### PR TITLE
update asyncpg example

### PR DESCRIPTION
**Pull request by r0fls**

### CODE REVIEW

**Comment by nszceta** [comment]
Why was the connection pool code removed?

**Comment by r0fls** [comment]
@nszceta because it doesn't make sense to open a connection pool for a single connection.

**Comment by r0fls** [comment]
If you can keep the same connection pool open and use that (which is possible by attaching it to the `request.app` attribute), then it would make sense to use it.

**Comment by nszceta** [comment]
@r0fls what are your thoughts regarding https://github.com/channelcat/sanic/issues/540 ?

**Pull request merged**
