### PR TITLE
add abort function

### PR DESCRIPTION
**Pull request by r0fls**
Address https://github.com/channelcat/sanic/issues/739

### CODE REVIEW

**Comment by pyx** [comment]
Should we have customizable message in `abort` then?

And what should we do if we raise something pre-defined, such as 404:
`abort(404)` does not raise `NotFound`, this is the inconsistency I talked about in #739 

Thanks for the quick action anyway.

**Comment by pyx** [comment]
To address that, we can look up the exception by the number, and use generic one if it is not defined, that's why I mentioned the "fast look up" in #739.
Then, it's actually more maintenance required then integer-based solution.

**Comment by r0fls** [comment]
@pyx I see what you mean. I'm going to update the PR so that it raises that. However can you elaborate more on what you mean by an integer based solution?

**Comment by pyx** [comment]
@r0fls sure, the preferred API is something like (*please be noted, this is my own personal view*):

```python
@app.route('/off-limit')
async def area51(request):
    abort(403)
    # or raise HTTPError(403)

@app.route('/wiki-leak')
async def top_secret(request):
    abort(410, "no longer exist')
    # or raise HTTPError(410, "no longer exist")

@app.error(403)
async def error403(error):
    return response.json({'error_code': error.status_code, 'message': error.message})
```

This way, all we need in sanic, is actual a mapping like so (very similar to what we already have):
```python
class HTTPError(Exception):  # or whatever base Exception
    ...

error_codes = {
...
403: "Forbidden",
404: "Not found",
...
410: "Gone",
}
```

And the default error handling is matching on the number, and look up the error message if not provided in the HTTPError exception instance or `abort` call.  No more defining each individual exceptions, no more testing in `abort` (to address the problem I mentioned above), any future addition of HTTP error code (albeit the situation is rare) will be handled by merely one more line in `error_codes`, etc.

That's why I prefer this design, and that's why I believe both Flask and Bottle were designed this way.

**Comment by pyx** [comment]
Correction:
The signature of error handlers should be:
```python
async def error_handler(request, error):
   ...
```

**Comment by r0fls** [comment]
@pyx yes I agree that would probably be better. However since it's a breaking change I'm just going to do this for now. We should begin a list of breaking changes we would consider introducing with the 0.x -> 1.x update though, e.g. 3.5 support.

**Comment by pyx** [comment]
@r0fls nicely done, thanks.

```python
SANIC_EXCEPTIONS = {}

def status_code(code):
    def class_decorator(cls):
        cls.status_code = code
        SANIC_EXCEPTIONS[code] = cls
        return cls
    return class_decorator

...

@status_code(404)
class NotFound(SanicException):
    pass

@status_code(400)
class InvalidUsage(SanicException):
    pass

...
```

This is my way to reduce duplication (not that it should be written this way).

But in either way, it cannot deal with exceptions sharing status code, such as `NotFound` and `FileNotFound`. I have no idea how to make it work now.

**Comment by r0fls** [comment]
@pyx we have to choose the more common exception in that case. If someone wants to raise a specific exception (e.g. URLBuildError or FileNotFound) they would have to do that explicitly: `raise FileNotFound("File not found")`. I added the suggested refactor, it's more lines of code, but I am happier to have `SANIC_EXCEPTIONS` at the top...

**Comment by r0fls** [comment]
It's really quite annoying that I can't define the `SANIC_EXCEPTIONS = {"foo": Bar}` before class `Bar` is defined 👿

**Comment by pyx** [comment]
@r0fls

Yes, seems it's used locally, maybe a name with lower case that begins with `_` .

The decorator does two things, 1. register the decorated class in SANIC_EXCEPTIONS, 2. add said status code as class attribute.
The first avoid the duplication of class name in defining SANIC_EXCEPTION, the second remove the duplication in defining `status_code` in class body so that you don't have to repeat the number which is error-prone. (so I use `pass` in class body if it only need `status_code`).

You sort of can define `SANIC_EXCEPTIONS` at the beginning. Put `SANIC_EXCEPTIONS` into a function scope, and call that function at the end of the file, assign the returned `SANIC_EXCEPTIONS` as `SANIC_EXCEPTIONS` in global scope. Please, don't try this at home.  :D

**Comment by pyx** [comment]
Excellent, just curious, why do we repeat the status_code in class body...

**Comment by r0fls** [comment]
thanks for the review!

**Pull request merged**
