### PR TITLE
Add url_bytes to Request

### PR DESCRIPTION
**Pull request by johndoe46**
For some application, we need to have access to the raw unparsed URL from the Request object.

### CODE REVIEW

**Comment by r0fls** [comment]
Why not just convert it back to the raw url afterwards?

**Comment by johndoe46** [comment]
That would be no "raw". We have no way to convert the URL back since some information is lost in the parsing done by parse_url.

Here are some urls we need to work with:

http://domain.tld/ark:/1234/567?
http://domain.tld/ark:/1234/567??

Note the question marks (yes, as crazy it seems, they're significant in the spec we have to implement). parse_url does this:

```
In [1]: from httptools import parse_url

In [2]: parse_url(b"http://domain.tld/ark:/1234/567")
Out[2]: <URL schema: b'http', host: b'domain.tld', port: None, path: b'/ark:/1234/567', query: None, fragment: None, userinfo: None>

In [3]: parse_url(b"http://domain.tld/ark:/1234/567?")
Out[3]: <URL schema: b'http', host: b'domain.tld', port: None, path: b'/ark:/1234/567', query: None, fragment: None, userinfo: None>

In [4]: parse_url(b"http://domain.tld/ark:/1234/567??")
Out[4]: <URL schema: b'http', host: b'domain.tld', port: None, path: b'/ark:/1234/567', query: b'?', fragment: None, userinfo: None>

```

**Comment by johndoe46** [comment]
Please Say Yes

**Comment by r0fls** [comment]
okcat

**Comment by johndoe46** [comment]
Awesome

**Pull request merged**
