### PR TITLE
fix multiple worker issue

### PR DESCRIPTION
**Pull request by r0fls**
addresses #594

### CODE REVIEW

**Comment by messense** [comment]
How is this gonna affect inflight connections?

**Comment by seemethere** [comment]
What exactly does this do?

**Comment by r0fls** [comment]
@seemethere if you look at the issue #594, as reported by a user in gitter, our implementation doesn't stop correctly on sigint. This fixes that.

**Comment by r0fls** [comment]
@messense this will probably not handle that correctly. However right now it's not even stopping, so still maybe a good idea...

**Comment by messense** [comment]
I don't think people would tend to use it in production if it does not handle graceful shutdown well. Maybe we should consider remove it?

**Comment by r0fls** [comment]
Going to have to rethink this. I don't think we'll be removing the multiple workers implementation entirely but it is starting to show serious weaknesses.

**Pull request closed without merging**
