### PR TITLE
provide initialized class for convenience

### PR DESCRIPTION
**Pull request by r0fls**
This makes usage more compact and still supports the old style of importing and instantiating the `Sanic` class directly.

### CODE REVIEW

**Comment by jiajunhuang** [comment]
I don't think it's a good design for a web framework. As a framework, we should provide classes, but not instances(of course, it's just my opinion).

**Comment by seemethere** [comment]
Yeah I'm not a fan of this either. Care to chime in @channelcat?

**Comment by r0fls** [comment]
Personally I think the Sanic community is taking the whole "explicit is better than implicit" thing a little too far. Remember the first line of PEP20 is "Beautiful is better than ugly". So, while there is a tradeoff to providing these types of conveniences, I think preserving and allowing the more expressive underlying methods, while still improving usability via removing unnecessary code is the right approach. The other issue where I feel this way is #69.

**Comment by r0fls** [comment]
I admit passing an instantiated class isn't beautiful, so there is that. However the upside is an improved API for interacting with Sanic, which I think is a win. I don't see a lot of use cases where it makes sense to customize the Sanic class instance. For example, when would a user want to supply their own, alternative router or error handling? None of the examples do this and I don't imagine many end users will. So, why not reduce code complexity, from a user's perspective?

**Pull request closed without merging**
