### PR TITLE
try to inject the app in add_task method

### LINKED ISSUE #1062: Accessing app in a background task
The example in the docs shows a nice way of scheduling a long-running task:

```python
async def notify_server_started_after_five_seconds():
    await asyncio.sleep(5)
    print('Server successfully started!')

app.add_task(notify_server_started_after_five_seconds())
```

If I've stashed my `notify_server_started_after_five_seconds()` function in `tasks.py`, What's the best way to access the `app` instance from it?

I've looked at dirty solutions like making `app` global... but I'm surprised that `app` and `loop` don't get injected like they do on the decorated methods.

Thanks in advance!

### PR DESCRIPTION
**Pull request by r0fls**
fixes #1062

### CODE REVIEW

**Comment by dvf** [comment]
This is great! 

If `loop.app` is always available, should we even accept `loop` as a secondary arg in the decorated tasks?

**Comment by r0fls** [comment]
That is a good question. Seems the primary reason is that the `app.loop` property waits to check if the loop is running. Not sure why that's there. Shouldn't be necessary.

**Comment by dvf** [comment]
Should we update the docs?

**Comment by r0fls** [comment]
https://github.com/channelcat/sanic/pull/1071

**Pull request merged**
