### PR TITLE
Clean up of examples. 

### PR DESCRIPTION
**Pull request by stopspazzing**
Removes non-core examples, optimizes, and formatted remaining to strictly follow PEP 8 styling guidelines. Non-Core examples will be moved to Wiki.

### CODE REVIEW

**Comment by stopspazzing** [comment]
Can an admin enable the Wiki please so I can move non-core examples? Takes 5 seconds to do. Thanks.

**Comment by seemethere** [comment]
Done

**Comment by seemethere** [comment]
Relates to #382

**Comment by stopspazzing** [comment]
https://github.com/stopspazzing/sanic/wiki/Examples

**Comment by seemethere** [comment]
@stopspazzing I'd say that's core.

Let me contact @channelcat about seeing about wiki edit permissions

**Comment by stopspazzing** [comment]
Reason I ask is because the client.py file requires an outside core import of 'requests' meaning that would have to be added to requirements.txt (or dev).

**Comment by r0fls** [comment]
@stopspazzing the wiki looks great

**Comment by stopspazzing** [comment]
I have added Projects to wiki @r0fls because of #396 
https://github.com/stopspazzing/sanic/wiki/Projects

**Comment by stopspazzing** [comment]
Any update on this?

**Comment by stopspazzing** [comment]
Would it be a good idea to move extensions list from docs to Wiki? Not core material...
https://github.com/channelcat/sanic/blob/master/docs/sanic/extensions.md

**Comment by stopspazzing** [comment]
Woot, wiki is enabled and editable:
https://github.com/channelcat/sanic/wiki

**Comment by seemethere** [comment]
@stopspazzing You might need to fix the merge conflict that has occurred and update the current extension wiki to include the new changes from the existing extension docs.

Particularly #782

**Comment by stopspazzing** [comment]
Done. Good to go.  `extensions.md` should be deleted after this merge.

**Pull request merged**
