### PR TITLE
Coverage report

### PR DESCRIPTION
**Pull request by yunstanford**
Add correct coverage report.

Current: 83%. You can see missing lines in the report.

### CODE REVIEW

**Comment by yunstanford** [comment]
https://github.com/channelcat/sanic/issues/781

tox -e py35

Name                  Stmts   Miss Branch BrPart  Cover   Missing
-----------------------------------------------------------------
sanic/__init__.py         4      0      0      0   100%
sanic/__main__.py        30     30      8      0     0%   1-44
sanic/app.py            337     56    144     16    80%   37-42, 76-80, 99, 220, 227-230, 240-241, 255, 270, 336, 347-353, 403, 456, 488, 505-511, 520-521, 573-575, 603, 614-633, 664-670, 672-674, 32->36, 36->37, 96->99, 219->220, 264->272, 269->270, 335->336, 402->403, 487->488, 564->567, 567->569, 572->573, 650->652, 662->664, 671->672, 723->726
sanic/blueprints.py     104      7     26      4    92%   73, 125, 150-151, 172-174, 68->73, 116->124, 124->125, 171->172
sanic/config.py          56      4     14      2    91%   97-98, 203-204, 96->97, 202->203
sanic/constants.py        1      0      0      0   100%
sanic/cookies.py         71      9     22      5    85%   28, 62, 91, 93, 100, 109-110, 117-118, 27->28, 54->62, 90->91, 92->93, 99->100
sanic/exceptions.py      56      3     16      1    94%   166-168, 209->214
sanic/handlers.py        99      6     32      3    93%   137, 142-143, 147-148, 152, 61->68, 136->137, 151->152
sanic/log.py             12      1      4      1    88%   11, 10->11
sanic/request.py        149     22     54     11    79%   11-17, 40, 112-113, 119-122, 131, 136, 162, 238, 240-241, 245-249, 253, 73->81, 97->115, 107->115, 127->131, 140->149, 160->162, 223->243, 236->240, 237->238, 244->245, 252->253
sanic/response.py       132     16     30      2    85%   6-7, 105-107, 272, 332-340, 353, 331->332, 352->353
sanic/router.py         173      5     82      5    96%   143, 190, 248, 258, 273, 142->143, 189->190, 247->248, 256->258, 272->273
sanic/server.py         269     47     80     15    78%   24-25, 50, 53, 56, 128-129, 133, 239-244, 275-286, 291, 301-306, 319, 321-322, 328-338, 355-358, 469-471, 480-481, 500, 503, 532-535, 127->128, 132->133, 134->136, 224->248, 233->239, 266->290, 290->291, 310->325, 316->319, 320->321, 499->500, 502->503, 522->531, 537->exit, 538->exit
sanic/static.py          61     13     32      7    72%   52, 65, 78, 84, 102-110, 115-116, 51->52, 64->65, 73->80, 77->78, 83->84, 101->102, 113->115
sanic/testing.py         71      8     10      1    89%   61-64, 71, 77-78, 84-85, 70->71
sanic/views.py           38      2     12      0    96%   105-106
sanic/websocket.py       48      4     10      2    90%   19, 29, 57-58, 18->19, 27->29
sanic/worker.py          94     22     18      3    74%   9-10, 15-16, 92, 95, 117-118, 125-132, 161-163, 166-168, 80->exit, 91->92, 94->95
-----------------------------------------------------------------
TOTAL                  1805    255    594     78    83%

**Comment by messense** [comment]
Might be worth to sleep for some more seconds in gunicorn worker test case.

https://github.com/channelcat/sanic/blob/master/tests/test_worker.py#L14

**Comment by yunstanford** [comment]
hmm, this test is very flaky. and it's not a good test pattern. we should not rely on such a condition.

**Comment by messense** [comment]
It's a integration test to ensure we don't break Gunicorn worker again and again as we did that a lot of times before.

Better way that sleeping may be wait until you can connect to the port or read `stdout` for some log to say it's up running.

**Comment by yunstanford** [comment]
>

**Comment by yunstanford** [comment]
going to create a separate one.

**Pull request closed without merging**
