### PR TITLE
Add Request.cancel_stream()

### PR DESCRIPTION
**Pull request by 38elements**

### CODE REVIEW

**Comment by r0fls** [comment]
@38elements is this not needed?

**Comment by r0fls** [comment]
It appears useful to me.

**Comment by 38elements** [comment]
@r0fls 
I am sorry.
If you think this is necessary,
Would you please implement this and send a pull request and merge.
I left this community at #714.
I only temporary return.
There is the problem which I refered at #714.
I leave this community.
Good luck!

**Comment by 38elements** [comment]
@r0fls 
I am sorry.
Since it is able to use `request.transport.close()`,
this change is unnecessary.

**Comment by 38elements** [comment]
@r0fls
I am sorry.
Since it is able to use request.transport.close(),
this change is unnecessary.

```
@app.post('/cancel_stream', stream=True)
async def cancel_stream(request):
    if condition:
        request.transport.close()
    result = ''
    while True:
        body = await request.stream.get()
        if body is None:
            break
        result += body.decode('utf-8')
    return text(result)
```

I left at #714.
I only temporary return.
There is a problem which I refered at #714.
I leave this community.

**Comment by r0fls** [comment]
ok @38elements thanks for reporting your findings

**Pull request closed without merging**
