### PR TITLE
Extract register_middleware into a method.

### PR DESCRIPTION
**Pull request by jrocketfingers**
I finally got to it, so here's an example of the idea suggested in #730.

Handily enough, the example itself is in the blueprints.py.

### CODE REVIEW

**Comment by 38elements** [comment]
I think this change is no effect.
The express only changed.
The change having no benefit should not be merged.

**Comment by jrocketfingers** [comment]
That's exactly why I'm proposing it. It affects nothing, yet gives us a better way to express the intent. Imho, readability is improved, for the price of free.

I can't help but ask, why exactly are you so hostile? Sanic could've been left in the state of it's initial commit*, and just had features plopped on until we've got an organically grown mass.

* haven't read the initial commit, I'm just trying to make a point about not changing anything.

**Comment by pyx** [comment]
https://github.com/channelcat/sanic/pull/732/commits/bf5438d5733c85c72dc092365a9570bdd2531e00#diff-c4444a35dbd5e37ee480b0e8888e0880L292

You could use
```python
partial(self.register_middleware, attach_to=middleware_or_request)
```
instead of `partial(Sanic.register_middleware, self, ...`

By not hard-coding the class name, the former works with subclasses as well.

A quick example:
```python
from functools import partial, wraps


class Deco:
    def log(self, func=None, *, before=True, after=True):
        if func is None:
            return partial(self.log, before=before, after=after)

        @wraps(func)
        def traced(*args, **kwargs):
            if before:
                print('calling <', func.__name__, '> with:', args, kwargs)
            result = func(*args, **kwargs)
            if after:
                print('result:', result)
            return result

        return traced


deco = Deco()


@deco.log
def total(*numbers):
    return sum(numbers)


@deco.log(after=False)
def output(*args):
    print(*args)


@deco.log(before=False, after=False)
def no_trace():
    print('no_trace called')


total(1, 2, 3, 4, 5)
print('-' * 20)
output("Hello,", "world!")
print('-' * 20)
no_trace()
```

output:
```
calling < total > with: (1, 2, 3, 4, 5) {}
result: 15
--------------------
calling < output > with: ('Hello,', 'world!') {}
Hello, world!
--------------------
no_trace called
```

**Comment by jrocketfingers** [comment]
@pyx, not sure how's the example related, since I'm trying to do the opposite [1], but yeah, thanks for pointing out the hardcoded `Sanic.register_middleware`!

That was a cop out early this morning, once the variant you suggested failed the tests. Now that I think about it, I think it was something along the lines of just putting `register_middleware` one indent back, without adding the `self` argument ;p

[1] we already have bound decorators, now I need to make that decorator return a partial to another bound method

**Comment by pyx** [comment]
@jrocketfingers Ha, it's my fault, I was banging out the code in a rush, I should have the inner function `traced` defined as a method of `Deco`, then it could be more in line with you code.

Yes, your latest change is what I mean by "works with subclasses."

**Comment by r0fls** [comment]
For the record, I think it's best to avoid nested functions that provide no benefit. They should be reserved for function factories, etc...

**Comment by jrocketfingers** [comment]
@r0fls, hence the PR, it was clear there was no actual benefit from having it nested, plus the change provides a clean way to register middleware (I utterly hate double parentheses

**Pull request merged**
