### PR TITLE
fix pipelining

### PR DESCRIPTION
**Pull request by r0fls**
Addresses https://github.com/channelcat/sanic/issues/337. 

```
$ wrk -t 10 -c 100 -d 10 -s pipeline.lua http://localhost:8000
Running 10s test @ http://localhost:8000
  10 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    47.21ms   31.48ms 174.15ms   71.39%
    Req/Sec     1.27k   641.14     4.04k    67.24%
  126848 requests in 10.06s, 15.00MB read
Requests/sec:  12608.15
Transfer/sec:      1.49MB
```

### CODE REVIEW

**Comment by r0fls** [comment]
@kolanos apparently you added the `cleanup` method, which doesn't seem necessary -- was there any reason for this, aside from it _seeming_ like a good idea? Cleaning up the connection is preventing it from being reused, which is in turn violating HTTP 1.1

**Comment by zkanda** [comment]
Haha, just removing cleanup can indeed resolve the pipeline issue.
But it's 78% slower on my machine without it.

With cleanup:

```
➜  sanic git:(master) ✗ wrk -t 1 -c 100 -d 10 http://localhost:8000                        <<<
Running 10s test @ http://localhost:8000
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.29ms  767.36us  12.59ms   61.52%
    Req/Sec    43.41k     2.80k   45.72k    89.00%
  432394 requests in 10.03s, 52.78MB read
Requests/sec:  43125.84
Transfer/sec:      5.26MB
```

Without cleanup:

```
➜  sanic git:(master) ✗ wrk -t 1 -c 100 -d 10 http://localhost:8000                        <<<
Running 10s test @ http://localhost:8000
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.07ms    7.34ms  60.46ms   67.29%
    Req/Sec     9.43k     6.52k   43.01k    89.00%
  93852 requests in 10.03s, 11.46MB read
Requests/sec:   9359.23
Transfer/sec:      1.14MB
```

**Comment by r0fls** [comment]
Derp :) I swear we need more tests...

**Comment by r0fls** [comment]
@zkanda btw thanks, I thought we had just gotten much slower :facepalm:

**Comment by kolanos** [comment]
@r0fls I can't remember the reasoning behind the cleanup method, so remove/alter as necessary.

**Comment by seemethere** [comment]
The cleanup method is so that keep-alive works as intended. After every request the variables that are set for the particular request should be cleaned up.

It's not a perfect implementation but it works for right now.

**Pull request closed without merging**
