### PR TITLE
Update Examples for 0.4.2

### PR DESCRIPTION
**Pull request by Sniedes722**
Updating examples to fit current docs. Will continue to update as many as I can before the next release.

### CODE REVIEW

**Comment by r0fls** [comment]
@Sniedes722 is this going to be a continued WIP then? That is will you be pushing the rest of the updates here, and we should hold on merging this for now?

**Comment by Sniedes722** [comment]
@r0fls Works by me. Do you have any release date goal for 0.4.2?

**Comment by r0fls** [comment]
The next release will be 0.5.0 and @seemethere says he should be able to next monday, but almost certainly sometime next week.

**Comment by r0fls** [comment]
Let's go ahead and merge this now. If you have more to contribute before the next release please open a new PR.

**Pull request merged**
