### PR TITLE
increase the timeout for test that fails

### PR DESCRIPTION
**Pull request by r0fls**
This test keeps failing intermittently (see https://github.com/channelcat/sanic/pull/871, https://github.com/channelcat/sanic/pull/870 and https://github.com/channelcat/sanic/pull/869)

Trying increasing the timeout.

### CODE REVIEW

**Comment by yunstanford** [comment]
is it a new test ? why did it happen ?  i've not looked deeply. but i can take a took tonight.

**Comment by r0fls** [comment]
@yunstanford ya, it's not new, just started failing sometimes out of the blue. We can disable it temporarily if needed.

**Comment by yunstanford** [comment]
yeah, the test is pretty stable in local box. but very flakey in travic ci.

**Comment by yunstanford** [comment]
@r0fls I figured it out. mainly because of travis ci is using a different `build dist`. i switched it back by specifying explicitly. https://github.com/channelcat/sanic/pull/873

**Pull request closed without merging**
