### PR TITLE
Added console logging statement to response handling block

### PR DESCRIPTION
**Pull request by jbcurtin**
I'd like to add this line so that exceptions will be logged to the console. If there is a better place to put this, please push back and I'll alter my PR accordingly. Performance wise, I'd like to adopt the naive viewpoint that this would be a non issue considering this logic executes only when an exception has been raised.

### CODE REVIEW

**Comment by Tim-Erwin** [comment]
I think this line should be two lines below. Besides that the (really) correct place to put this is probably in  `exceptions.py:Handler:default`.

**Comment by Tim-Erwin** [comment]
Ups, forget the first sentence, that was a bit premature.

**Comment by seemethere** [comment]
I'd agree with @Tim-Erwin here

**Comment by seemethere** [comment]
This was done in #306

**Pull request closed without merging**
