### PR TITLE
add websocket support

### PR DESCRIPTION
**Pull request by r0fls**
Addresses #12. For temporary websocket support we could do something like this, simply using the websockets module.

### CODE REVIEW

**Comment by r0fls** [comment]
I guess one concern would be maintaining backward compatibility once we've implemented our own solution. However I think we can issue a deprecation statement leading up to our eventual transition to a different API.

**Comment by seemethere** [comment]
Would this be better served as an extension?

**Comment by r0fls** [comment]
Well, it seems it already exists as an extension. I just think providing an intuitive interface would help users. As opposed to overloading the `before_start` function with many use cases, as we've been advising people to. That seems sloppy to me. 

However, I'm thinking it would make sense to add a general method, like:

```
app.ensure_future(task)
```
This would allow you to do:

```python
import websockets
import random
import datetime
from sanic import Sanic
from sanic.response import text

async def time(websocket, path):
    while True:
        now = datetime.datetime.utcnow().isoformat() + 'Z'
        await websocket.send(now)
        await asyncio.sleep(random.random() * 3)

start_server = websockets.serve(time, '127.0.0.1', 5678)
app = Sanic()
app.ensure_future(start_server)
@app.get()
def hello(request):
    return text('OK')

app.run()
```

@seemethere would you be able to get behind that instead?

**Comment by r0fls** [comment]
https://github.com/r0fls/sanic-websockets/tree/master

**Pull request closed without merging**
