### PR TITLE
add jinja example

### PR DESCRIPTION
**Pull request by r0fls**
#113

### CODE REVIEW

**Comment by seemethere** [comment]
@r0fls I don't think this is the commit you meant to push up o.O

**Comment by r0fls** [comment]
@seemethere thank you, you are a smart man. Completely unrelated to this issue -- is there a roadmap for the next major or minor release somewhere? Or a discussion about doing versioned branches? How are we dealing with versioning?

**Comment by seemethere** [comment]
@r0fls Nothing concrete just yet, been thinking over it. I'll post my thoughts up probably by Wednesday or Thursday.

**Comment by seemethere** [comment]
Closes #113

**Pull request merged**
