### PR TITLE
Fixed token attribute

### PR DESCRIPTION
**Pull request by Sniedes722**
Originally referenced in #502, this updates token in line with other parsed request attributes and also updates the test to reflect how token type and value should both be asserted.

### CODE REVIEW

**Comment by Sniedes722** [comment]
@r0fls I'm ok with this too. This token attribute has honestly been holding me back from building an Oauth lib. Separating the token type from the token itself (like you've done) is honestly much better.

**Comment by r0fls** [comment]
@Sniedes722 ok that makes sense. Awesome you're working on an oauth library since we need auth extensions. Please make a PR with a link to it once you're ready. 

Regarding this PR, I think this works better for what you need from Sanic: https://github.com/channelcat/sanic/pull/656. Otherwise there isn't much purpose to the token attribute (since you can access the same thing directly with the Authorization header).

**Comment by r0fls** [comment]
You can see from the tests in the other PR that it accepts: Bearer Token <TOKEN>, Token <TOKEN>, and <TOKEN> and produces <TOKEN> in all three cases. I think this is the best of both worlds.

**Comment by Sniedes722** [comment]
@r0fls haven't disagreed yet my friend.

**Pull request closed without merging**
