### PR TITLE
remove port from ip

### PR DESCRIPTION
**Pull request by r0fls**
fixes https://github.com/channelcat/sanic/issues/968

### CODE REVIEW

**Comment by r0fls** [comment]
Hmm looks like maybe flake8 got more stringent about the bare except

**Comment by messense** [comment]
Bare except is bad. If you intend to catch `BaseException` just write `except BaseException:`, but most of the time it's a bad idea to catch `BaseException`.

**Comment by r0fls** [comment]
@messense ya but the thing is, I didn't add or change anything with exceptions 🤔 this just started failing out of the blue

**Comment by r0fls** [comment]
Also in these cases I'm pretty sure the exception is intentionally a catch-all. You don't want the server to die because we didn't think of all the possible exceptions that could happen. It should just log them, presumably, in most of these cases.

**Comment by messense** [comment]
It's caused by new version of `flake8`. http://flake8.pycqa.org/en/latest/release-notes/3.5.0.html#new-dependency-information

> Start using new PyCodestyle checks for bare excepts and ambiguous identifier

**Comment by messense** [comment]
bare except or `except BaseException:` will also catch `KeyboardInterrupt` and some other exceptions which are usually not what people expected.

**Comment by messense** [comment]
FYI. [Exception hierarchy](https://docs.python.org/3/library/exceptions.html#exception-hierarchy)

```
BaseException
 +-- SystemExit
 +-- KeyboardInterrupt
 +-- GeneratorExit
 +-- Exception
      +-- StopIteration
      +-- StopAsyncIteration
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
      +-- AssertionError
      +-- AttributeError
      +-- BufferError
      +-- EOFError
      +-- ImportError
           +-- ModuleNotFoundError
      +-- LookupError
      |    +-- IndexError
      |    +-- KeyError
      +-- MemoryError
      +-- NameError
      |    +-- UnboundLocalError
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      |    +-- ConnectionError
      |    |    +-- BrokenPipeError
      |    |    +-- ConnectionAbortedError
      |    |    +-- ConnectionRefusedError
      |    |    +-- ConnectionResetError
      |    +-- FileExistsError
      |    +-- FileNotFoundError
      |    +-- InterruptedError
      |    +-- IsADirectoryError
      |    +-- NotADirectoryError
      |    +-- PermissionError
      |    +-- ProcessLookupError
      |    +-- TimeoutError
      +-- ReferenceError
      +-- RuntimeError
      |    +-- NotImplementedError
      |    +-- RecursionError
      +-- SyntaxError
      |    +-- IndentationError
      |         +-- TabError
      +-- SystemError
      +-- TypeError
      +-- ValueError
      |    +-- UnicodeError
      |         +-- UnicodeDecodeError
      |         +-- UnicodeEncodeError
      |         +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
           +-- ImportWarning
           +-- UnicodeWarning
           +-- BytesWarning
           +-- ResourceWarning
```

**Comment by r0fls** [comment]
Well, I agree we could do better here. But I wasn't intending to touch that, so I'm going to hold off on improvements to the exception handling. If you have any comments about the socket/ip/port implementation though, I'll leave this open a bit longer.

**Pull request merged**
