### PR TITLE
Fixes route overloading for dynamic routes

### PR DESCRIPTION
**Pull request by seemethere**
# Overview

Addresses #353, now dynamic routes work alongside our newly minted
overloaded routes! Also fixed an unintended side effect where methods
were still being passed in as None for `Sanic.add_route`.

I'll add in some tests so this shouldn't be merged until I add this in.

### CODE REVIEW

**Comment by seemethere** [comment]
Actually, this doesn't fully work with HTTPMethodView, due to the way it gets added. Maybe it would be better to just have an add_view function that dynamically gets what methods the view is allowed for? What do you think @AntonDnepr?

**Comment by seemethere** [comment]
Actually have a fix for HTTPMethodView, but it isn't ideal. Also for some reason calls to `HEAD` method endpoints don't work for me locally. 🤔

**Comment by r0fls** [comment]
@seemethere how're you testing the HEAD method? This works for me:

```python
from sanic import Sanic
from sanic.response import text

app = Sanic()

@app.head("/")
async def test(request):
    return text("OK")

app.run()
```

```bash
$ curl --head localhost:80
00
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 2
Connection: keep-alive
Keep-Alive: timeout=60
```

**Comment by seemethere** [comment]
@r0fls I figured it out, the `HEAD` method doesn't return a body so trying to verify the body would be useless. Instead I just switched the test to verify the headers!

**Comment by r0fls** [comment]
OK, I vote we add this test case:

```python
from sanic import Sanic
from sanic.response import text
from sanic.utils import sanic_endpoint_test
from sanic.router import RouteExists
import pytest

@pytest.mark.parametrize("method,attr, expected", [
        ("get", "text", "OK1 test"),
        ("post", "text", "OK2 test"),
        ("put", "text", "OK2 test"),
        ("delete", "status", 405),
])
def test_overload_dynamic_routes(method, attr, expected):
    app = Sanic('test_dynamic_route')

    @app.route('/overload/<param>', methods=['GET'])
    async def handler1(request, param):
        return text('OK1 ' + param)

    @app.route('/overload/<param>', methods=['POST', 'PUT'])
    async def handler2(request, param):
        return text('OK2 ' + param)


    request, response = sanic_endpoint_test(app,
                                            method,
                                            uri='/overload/test')
    assert getattr(response, attr) == expected
```

Then open an issue when we close the other one, and include this test case:

```python
def test_overload_dynamic_routes_exist():
    app = Sanic('test_dynamic_route')

    @app.route('/overload/<param>', methods=['GET'])
    async def handler1(request, param):
        return text('OK1 ' + param)

    @app.route('/overload/<param>', methods=['POST', 'PUT'])
    async def handler2(request, param):
        return text('OK2 ' + param)


    # if this doesn't raise an error, than at least  assert response.text == 'Duplicated' should happen.
    # but neither do
    with pytest.raises(RouteExists):
        @app.route('/overload', methods=['PUT', 'DELETE'])
        async def handler3(request):
            return text('Duplicated')

    request, response = sanic_endpoint_test(app,
                                            'PUT',
                                            uri='/overload/test')
    assert response.text == 'Duplicated'
```

Unless we can get this to pass the second test before we merge this.

**Comment by youknowone** [comment]
Thanks for a nice fix. Now I learned I tried a stupid way than an easy way.

About routing handlers, I suggest:
- class-based view can be a default view handler
- Add common method handler getter to both HTTPMethodView and CompositionView
- Add a wrapper or attribute to function handlers

Then they will share same interface as router's point of view.

About the get-handler overhead, I think `Router._get` can cache them with uri+method input to specific handler function output.

**Comment by seemethere** [comment]
@youknowone I think we can simplify the views portion as well as the adding routes portion, for this PR though I think it's good to focus on the hot-fix for dynamic route overloading.

**Comment by youknowone** [comment]
I also definitely agree about this PR. sorry for making confusion.

**Comment by seemethere** [comment]
@r0fls I'll add those test cases tomorrow and then push up 0.3.1. Don't merge until I push up the test cases.

**Comment by seemethere** [comment]
Test cases have been put in, will merge and roll into `0.3.1` later today.

**Pull request merged**
