### PR TITLE
Fixed plotly_example, now works

### PR DESCRIPTION
**Pull request by stopspazzing**
Old file didn't work because was half finished. Didn't need to have  5+ more dependencies just for a simple example.
Remember: K.I.S.S

### CODE REVIEW

**Comment by Sniedes722** [comment]
@stopspazzing just ported the flask example originally...

**Comment by Sniedes722** [comment]
@stopspazzing thanks for simplying the example, but any idea why I'm getting this error while trying to run it?
```terminal
  import plotly
  File "/usr/local/lib/python3.5/dist-packages/plotly/__init__.py", line 31, in <module>
    from plotly import (plotly, dashboard_objs, graph_objs, grid_objs, tools,
  File "/usr/local/lib/python3.5/dist-packages/plotly/plotly/__init__.py", line 10, in <module>
    from . plotly import (
  File "/usr/local/lib/python3.5/dist-packages/plotly/plotly/plotly.py", line 29, in <module>
    from plotly import exceptions, files, session, tools, utils
  File "/usr/local/lib/python3.5/dist-packages/plotly/tools.py", line 60, in <module>
    matplotlylib = optional_imports.get_module('plotly.matplotlylib')
  File "/usr/local/lib/python3.5/dist-packages/plotly/optional_imports.py", line 23, in get_module
    return import_module(name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.5/dist-packages/plotly/matplotlylib/__init__.py", line 14, in <module>
    from plotly.matplotlylib.renderer import PlotlyRenderer
  File "/usr/local/lib/python3.5/dist-packages/plotly/matplotlylib/renderer.py", line 13, in <module>
    import plotly.graph_objs as go
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/__init__.py", line 14, in <module>
    from plotly.graph_objs.graph_objs import *  # this is protected with __all__
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_objs/graph_objs.py", line 34, in <module>
    from plotly import exceptions, graph_reference
  File "/usr/local/lib/python3.5/dist-packages/plotly/graph_reference.py", line 232, in <module>
    @utils.memoize()
  File "/usr/local/lib/python3.5/dist-packages/plotly/utils.py", line 492, in memoize
    return decorator(_memoize)
  File "/usr/lib/python3/dist-packages/decorator.py", line 213, in decorator
    fun = getfullargspec(callerfunc).args[0] # first arg
IndexError: list index out of range```

**Comment by seemethere** [comment]
Seems to work for me:
screen shot 2017-05-12 at 10 58 49 am

Python 3.6.1 though

**Comment by Sniedes722** [comment]
@seemethere version seemed to fix it, I wonder if that's why the old example didn't work being 3.5

**Comment by stopspazzing** [comment]
Just tested with `3.6.1` and `3.5.2` from a fresh git clone, I run into no issues? Can you post your plotly version?

**Comment by 38elements** [comment]
@seemethere  @Sniedes722 
I think this example is needless.
Old version used sanic extensions.
Current version does not use.

**Comment by stopspazzing** [comment]
makes sense, is there a need for ALL the other examples while we are on topic?

**Comment by 38elements** [comment]
I have not said other examples.
I am talking about this example.
This example seems to explain only how to use `plotly.offline.plot()`.
There is no reason to need this example.

**Comment by Sniedes722** [comment]
@38elements @stopspazzing the original example I posted was ported to Sanic from Plotly's official flask example. I had just used Jinja for templating.

**Comment by 38elements** [comment]
Would you tell me that `plotly.offline.plot()` is asynchronous or not?

**Comment by 38elements** [comment]
I think the old version example is needless.
I think it is not appropriate reason that there is example of flask.

**Comment by 38elements** [comment]
This is related to #627.

**Comment by Sniedes722** [comment]
@38elements I didn't use that in the original example...

**Comment by stopspazzing** [comment]
So... just delete it and move on with life?

**Comment by Sniedes722** [comment]
agree strongly!

**Pull request merged**
