### PR TITLE
Updating examples for 0.5.0

### PR DESCRIPTION
**Pull request by Sniedes722**
Trying to continue to update docs based on the current docs.

### CODE REVIEW

**Comment by Sniedes722** [comment]
Travis build is failing due to unrelated tests.

**Comment by seemethere** [comment]
Should be fixed after #626, just make sure to merge those changes in with yours

**Comment by Sniedes722** [comment]
@seemethere does it make sense to keep this open for a bit?

**Comment by r0fls** [comment]
@Sniedes722 are you planning to add more to it?

**Comment by Sniedes722** [comment]
@r0fls will throw in a few more over the next couple days.

**Comment by Sniedes722** [comment]
Updated basic examples to be in-line with the docs. Also added a detailed example, a port of [Plotly's Flask Example](https://github.com/plotly/plotlyjs-flask-example) to Sanic, for browser-based graphs using pandas, numpy, and some Sanic extensions. I'll open a new request whenever I have time to add more.

**Comment by 38elements** [comment]
@seemethere @r0fls 
Would you please check this pull request?
I think most of the changes are unnecessary.

**Comment by Sniedes722** [comment]
@38elements it seems like the only qualm you have is that I used responses **exactly** like the docs list them:
```python
import response

@app.route("/")
async def index(request):
    return response.response_type()

```

**Comment by r0fls** [comment]
@Sniedes722 @38elements I personally often use them that way (`from sanic import response`). However if we want to standardize the usage pattern (in either direction) I'm ok with that. Beyond that, I can see @38elements's point that adding examples that don't exhibit sanic functionality aren't necessary. I agree the plotly example might make more sense as its own extension or gist, in order to keep the examples focusing on sanic features.

**Comment by 38elements** [comment]
I think changing `text()` to `response.text()` is needless.
This change cause losting consistency.

I thought that implicit standards for  adding examples existed.
I thought that the example is one of the following.

* Example of how to use Sanic

* Example of how to use Sanic extensions

* Example of how to use Sanic and asynchronous library

**Comment by r0fls** [comment]
@38elements yes I think that is a fair assumption. The examples obviously aren't part of the core, so the approval is less strict in that area. However I understand your concern.

**Pull request merged**
