### PR TITLE
Patch logging refactor

### PR DESCRIPTION
**Pull request by yunstanford**
do less for logging.

### CODE REVIEW

**Comment by r0fls** [comment]
@yunstanford does this PR improve baseline performance? Can you post a benchmark?

**Comment by yunstanford** [comment]
it has nothing to do with perf improvement. this pr just refactored the logging pattern, setup, disable, etc.
As for performance, it really depends on logging infra or how user wanna setup the logging. i'd like to let user make the choice.

**Comment by yunstanford** [comment]
Resolved conflicts.

**Comment by r0fls** [comment]
@yunstanford sorry can you resolve the conflicts one more time please?

**Comment by yunstanford** [comment]
ok, resolved.

**Pull request merged**
