### PR TITLE
A very basic implementation of a shared resource, app.shared (#129)

### PR DESCRIPTION
**Pull request by atribecalledkwest**
I'm sure there is a major flaw in these 6 lines of changes to make #129 a thing, but it seems to work.

### CODE REVIEW

**Comment by pahaz** [comment]
In my opinion the `app` object represent the application state and shared resource storage.
And if we change line:
https://github.com/channelcat/sanic/pull/132/commits/78707608fb6a5a34330f81cf3222ac9829146e9c#diff-ac7b7152eadc8343e3f10d4780d9a678R177
```
request.shared = self.shared
```
to 
```
request.app = self
```

It would be better and more clear approach. (But it may have effect to performance)

**Comment by guidiego** [comment]
Any update on that issue?

**Comment by guidiego** [comment]
@pahaz I need that cuz we are trying to use Sanic on prod! I do the modifications [here](https://github.com/iclinic/sanic), if you want and if @atribecalledkwest not appear I can do the PR :)

**Comment by pahaz** [comment]
@guidiego . Yes, I understand your problem. I am also use it! This is really a problem.

What do you think about the `request.app`? Is it solve your problem?

**Comment by guidiego** [comment]
Hey @pahaz, so after try some implementations I'm not sure about this will solve my problem. It's totally useful to some contexts, but I ask myself if this `shared` it's the correct thing to do! 

I think that we need this implementation in the most part of cases to transport db contexts and configuration variables to the rest of application, I had to use `python-decouple` and import the file inside the places that I need some "shared contexts" because the Sanic is not totally environment agnostic.

We can discuss about some Flask implementations, like, `from_file`, `from_json` and `from_folder` to set APP shared contexts :) And how we can Implement this most useful with a kind of good pratices like `create_app` and `manages funcs` :D

Let me know if I can help you in something, I think that we can create a gitter for improve the contact :D

**Comment by seemethere** [comment]
Closing, I think the implementation in #163 is a bit better for this.

**Pull request closed without merging**
