### PR TITLE
Added RFC 7233 Range HTTP/1.1 Range Requests (again)

### PR DESCRIPTION
**Pull request by aquacash5**
Hey all,

I am currently rewriting my youtube to podcast web app using sanic. I noticed that the implementation of static files doesn't include a way to deal with range requests [RFC 7233](https://tools.ietf.org/html/rfc7233). So instead of writing my own implementation for my app, I tried to implement it directly into sanic.

### CODE REVIEW

**Comment by r0fls** [comment]
@aquacash5 are you able to rebase this down to 1 commit? You can do `git rebase -i HEAD~17` (or maybe 16, it should only show your commits).

Then, you'll see something like:

```
pick b74056d commit message...
pick b781a4b commit message...
pick 3cd5b83 yada yada...
...
```

Change all of the `pick` to `f` except 1 of them, and then update it's commit message accordingly.

**Comment by r0fls** [comment]
@aquacash5 whoops, sorry! I didn't mean to have you close it :) We can probably rebase it for you if it's not working for you...

**Comment by aquacash5** [comment]
@r0fls sorry I just am having a lot of trouble with git.

**Comment by aquacash5** [comment]
It is funny. All this work just to get this range parser built in, so I can use it for my podcast app.

**Comment by r0fls** [comment]
@aquacash5 speaking of more work :/ sorry but can you close/reopen this with just your 17 commits? We'll handle squashing them.

**Comment by r0fls** [comment]
BTW we've all been there, but Git is obviously super helpful for collaborating so it's worth the uphill battle.

**Comment by seemethere** [comment]
Yeah I'd suggest just making a new branch off your local master and then copying the changes over to it. I was going to squash and merge anyway so don't worry about the previous commit history.

Just do a `git checkout master` & `git pull upstream master` `git checkout -b new_feature_branch` and then copy your changes there and push it back up. I'd really like to get this change in.

**Comment by seemethere** [comment]
Going to close this in anticipation of a new PR.

**Pull request closed without merging**
