### PR TITLE
default to auto_reload in debug mode

### PR DESCRIPTION
**Pull request by r0fls**
fixes: https://github.com/channelcat/sanic/issues/1158

### CODE REVIEW

**Comment by arnulfojr** [comment]
@r0fls now that the `auto_reload` option is set to True in debug mode, maybe we can add it to the documentation? I have created a PR for it if you have any ideas or feedback it will be welcomed :)

**Comment by r0fls** [comment]
hmm i rebased but the build is still hanging

**Comment by r0fls** [comment]
@yunstanford any ideas?

**Comment by Yaser-Amiri** [comment]
oops! @r0fls we can't do this now! We talked [here](https://github.com/channelcat/sanic/pull/1047#discussion_r159031631) before. Enabling auto-reloading causes failing some tests those need DEBUG=True so I separated DEBUG mode from auto-reloading.

**Comment by r0fls** [comment]
@Yaser-Amiri thanks for the heads up, I just disabled `auto_reload` in the test client for now: https://github.com/channelcat/sanic/pull/1159/files#diff-8ff5a7907a8a3e558aa2868b65263a87R48

**Pull request merged**
