### PR TITLE
Upgrade development status to beta

### PR DESCRIPTION
**Pull request by manisenkov**
Fix for #1103

### CODE REVIEW

**Comment by r0fls** [comment]
🤔  what's up with these failed tests

**Comment by manisenkov** [comment]
🤷‍♂️ seems not related to changes in this PR

**Comment by manisenkov** [comment]
run tests locally, looks like problem is related to this: https://github.com/pytest-dev/pytest/issues/3170

**Comment by r0fls** [comment]
Why did it start out of nowhere though? 🤔  Although I agree it's unrelated, as a policy we don't merge PRs with failed tests...

**Comment by manisenkov** [comment]
I made PR (https://github.com/channelcat/sanic/pull/1108) with pinned version of `pytest`: https://github.com/channelcat/sanic/pull/1108, or one could wait until fix (https://github.com/Frozenball/pytest-sugar/pull/133) for `pytest-sugar` will be released.

**Comment by manisenkov** [comment]
I've rebased PR, now it's 🍏

**Pull request merged**
