### PR TITLE
WIP: Live Reload

### PR DESCRIPTION
**Pull request by seemethere**
This will the be the PR to track progress on the live reload feature as highlighted in #168 

# Notes:
### Things that need to be thought about for this feature are:
- How to effectively start / stop the app with the observer
  - Can we do it without having to do a subprocess call? (Probably not)
- What should we watch? (Is it all of `sys.path` like Flask? Or should it just the directory (recursive) of the original caller?)
- Should this be a part of `0.4.0` or should we cut a release for `0.4.0` and just roll this in for a possible `0.5.0`? (Probably `0.5.0`)
- Should watchdog be a soft-dependency? (I vote yes for this one)

### Things that have already been tried:
- Reusing the ReloaderLoop from `werkzeug` (Doesn't work with the signal handlers)

### Things that should be considered:
- Maybe we don't write any live_reload code and just document ways to do live reload like:
  - Using commands similar to http://entrproject.org/, http://pm2.keymetrics.io/ (from @mkorkmaz)

### CODE REVIEW

**Comment by subyraman** [comment]
Awesome. I'd be in favor of making live reload a hard dependency, this is one of those development tools that people can reasonably expect and makes the dev cycle a lot easier.

Watching `sys.path` sounds good so that the entire app isn't reloading when static resources change.

**Comment by r0fls** [comment]
So does this branch work for live reload?

**Comment by seemethere** [comment]
@r0fls Not fully yet

Right now it just has the file system handlers but it'll need a reloader loop to fully function but I think I might just scrap the idea and tell users to use external commands like `entr` or `pm2` if they want live reload.

I don't think the complexity of writing into the main package is worth it.

**Comment by r0fls** [comment]
Ya, if we can just maybe have a section in the docs that explains how to do it and it's not too crazy to, that would probably be better I agree.

**Comment by seemethere** [comment]
Yeah if it's as simple as:

```console
$ ls * | entr -r python my_app.py
```

Then I don't see why implementing live reload would be necessary.

**Comment by lixxu** [comment]
@seemethere better to have if develop under Windows, or someone make an extension

**Comment by messense** [comment]
With Gunicorn worker, reload is simple:

```
gunicorn --reload --bind localhost:8000 --worker-class sanic.worker.GunicornWorker app:app
```

**Comment by webtic** [comment]
Is anyone using entr with MacOS? 
A `ls -d server.py | entr python3 server.py` is picking up any changes for me on 10.11.6

**Pull request closed without merging**
