### PR TITLE
add release notes to docs

### PR DESCRIPTION
**Pull request by lixxu**

### CODE REVIEW

**Comment by lixxu** [comment]
@r0fls if it's not a good idea to add this release notes to doc, I'll close it.

**Comment by r0fls** [comment]
ok if you agree with @lcDotcom then that's fine. I would agree if it's going to require updating two places, let's keep the work required to maintain things minimal unless it adds a lot of good functionality.

**Comment by r0fls** [comment]
However if there is a good reason for this and others are interested in it, please leave it open so it can be further discussed. It's up to you.

**Comment by r0fls** [comment]
I am undecided here. @seemethere what's your opinion? He's been managing the releases and I think he said that he prefers to keep it in one place.

**Comment by r0fls** [comment]
uh oh, i think the rebase went wrong. I guess I vote we close this since there was objection from @lcDotcom and I suspect @seemethere doesn't want any extra work when he's releasing the latest version...

**Comment by lixxu** [comment]
I'll close it.

**Pull request closed without merging**
