### PR TITLE
Remove utils.py

### PR DESCRIPTION
**Pull request by 38elements**
Since current version is 0.5.2, this removes `sanic_endpoint_test()`.

### CODE REVIEW

**Comment by r0fls** [comment]
@38elements do you know why the build is failing? I'm going to revert this for now though it actually looks like a glitch or travis error, rather than a failed sanic test.

**Comment by r0fls** [comment]
not sure what happened here https://travis-ci.org/channelcat/sanic/jobs/228624689#L123-L125:

```
3.44s$ git fetch origin +refs/pull/690/merge:
fatal: Couldn't find remote ref refs/pull/690/merge
Unexpected end of command stream
```

**Comment by r0fls** [comment]
oh derp i think i must have merged it originally before the tests passed and then it deleted the branch :(

**Comment by r0fls** [comment]
actual build is passing, sorry, we're good to go

**Comment by 38elements** [comment]
@r0fls 
Thank you for verifing.

**Pull request merged**
